name = "AlgoritmiStruttureDati"
uuid = "c8a0b69e-4f51-43a1-9b75-c43b104b7395"
authors = ["Lorenzo Feroleto"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
